name: ULO Autobuilder v2

on:
  workflow_dispatch:
    inputs:
      kernel:
        description: 'Kernel Version (ex. 6.6.6, 6.1.31-localversion)'
        required: true
        default: '6.1.66-DBAI'
        type: string
      rootfs:
        description: 'ROOTFS File (ex. ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz)'
        required: true
        default: 'ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz'
        type: string
      rootfs_size:
        description: 'ROOTFS Size, min 640 (756, 1024, 2048, etc)'
        required: true
        default: '1024'
        type: string
      fwinfo:
        description: 'Firmware Information'
        required: true
        default: 'release note'
        type: string

jobs:
  build_ipk:
    permissions:
      contents: write
    name: ULO Autobuilder
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device:
          - s905x
          - h618-orangepi-zero3  # Batasi untuk testing
    steps:
      - name: Cleanup and Installing Prerequisites
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install jq lolcat build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget aria2
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Cache ULO repository
        uses: actions/cache@v4
        with:
          path: |
            core/
            rootfs/
            device/
          key: ${{ runner.os }}-ulo-repo-${{ hashFiles('ulo') }}

      - name: Patching ULO
        run: |
          mv ./.github/workflows/ULO_Workflow.patch ./ULO_Workflow.patch
          patch -p1 < ./ULO_Workflow.patch

      - name: Building OpenWrt
        run: |
          echo "Checking ULO repository availability..."
          curl -I https://codeload.github.com/armarchindo/ULO-repository/zip/refs/heads/main
          sudo ./ulo -y -m ${{ matrix.device }} -r ${{ inputs.rootfs }} -k ${{ inputs.kernel }} -s ${{ inputs.rootfs_size }} || \
          (sleep 5 && sudo aria2c --max-tries=3 --retry-wait=5 https://codeload.github.com/armarchindo/ULO-repository/zip/refs/heads/main)
          echo "Build completed or failed. Checking output directory..."
          ls -la ./out/

      - name: Creating Package Artifact
        if: success() || failure()
        run: |
          mkdir -p ./artifact/${{ matrix.device }}
          cp -rf ./out/${{ matrix.device }}/* ./artifact/${{ matrix.device }}/ || true

      - name: Delivering Package
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: openwrt_package_${{ matrix.device }}
          path: ./artifact/${{ matrix.device }}/*

      - name: Upload release asset
        if: success()
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./artifact/${{ matrix.device }}/*
          tag: ${{ matrix.device }}
          file_glob: true
          overwrite: true
          body: |
            ## OpenWrt Release for ${{ matrix.device }} devices
            ULO-Builder Release from Github Workflow
            ### OpenWrt Image Information
            - Firmware Details:
              - Device type: ${{ matrix.device }}
              - Kernel version: ${{ inputs.kernel }}
              - ROOTFS File: ${{ inputs.rootfs }}
              - ROOTFS Size: ${{ inputs.rootfs_size }}
            - Firmware Information:
              - ${{ inputs.fwinfo }}
