name: ULO Autobuilder v2 (Flexible Options)

on:
  workflow_dispatch:
    inputs:
      rootfs_choice:
        description: 'Pilih RootFS yang akan dibuild atau pilih "custom" untuk menggunakan URL'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz
          - OpenWrt-23.05.4-A2OS-armsr-armv8-generic-rootfs.tar.gz
          - OpenWrt-23.05.4-ALKHANET-armsr-armv8-generic-rootfs.tar.gz
          - OpenWrt-23.05.5-ALKHANET-armsr-armv8-generic-rootfs.tar.gz
          - OpenWrt-23.05.5-InsomWRT-armsr-armv8-generic-rootfs.tar.gz
          - custom
      
      custom_rootfs_url:
        description: 'URL download RootFS (Gunakan tautan dari GDrive, Mega, atau hotlink)'
        required: false
        type: string

      device_choice:
        description: 'Pilih Device & Kernel (pilih "all" untuk build semua)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          # --- Amlogic ---
          - 'Amlogic: s905x (Kernel 6.1.66-DBAI)'
          - 'Amlogic: s905x (Kernel 4.9.337)'
          - 'Amlogic: s905x2 (Kernel 6.1.66-DBAI)'
          - 'Amlogic: s905x2 (Kernel 5.4.279)'
          - 'Amlogic: s905x2 (Kernel 4.9.337)'
          - 'Amlogic: s905x3 (Kernel 6.1.66-DBAI)'
          - 'Amlogic: s905x4 (Kernel 6.1.66-DBAI)'
          - 'Amlogic: s905x4 (Kernel 5.4.279)'
          # --- Rockchip ---
          - 'Rockchip: rk3588s-orangepi-5 (Kernel 5.10.160-rk35v-dbai)'
          - 'Rockchip: rk3566-orangepi-3b (Kernel 5.10.160-rk35v-dbai)'
          - 'Rockchip: rk3588-orangepi-5-max (Kernel 5.10.160-rk35v-dbai)'
          - 'Rockchip: rk3588-orangepi-5-plus (Kernel 5.10.160-rk35v-dbai)'
          # --- Allwinner ---
          - 'Allwinner: h618-orangepi-zero3 (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: h618-orangepi-zero3 (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: a64-bananapi-m64 (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: a64-bananapi-m64 (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: a64-nanopi-a64 (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: a64-nanopi-a64 (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: h313-x96q-lpddr3 (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: h313-x96q-lpddr3 (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: h5-orangepi-pc2 (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: h5-orangepi-pc2 (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: h5-orangepi-prime (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: h5-orangepi-prime (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: h5-orangepi-zeroplus (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: h5-orangepi-zeroplus (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: h5-orangepi-zeroplus2 (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: h5-orangepi-zeroplus2 (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: h6-orangepi-1plus (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: h6-orangepi-1plus (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: h6-orangepi-3 (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: h6-orangepi-3 (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: h6-orangepi-3lts (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: h6-orangepi-3lts (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: h6-orangepi-lite2 (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: h6-orangepi-lite2 (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: h6-tanix-tx6 (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: h6-tanix-tx6 (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: h616-orangepi-zero2 (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: h616-orangepi-zero2 (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: h616-x96-mate (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: h616-x96-mate (Kernel 6.1.31-AW64-DBAI)'
          - 'Allwinner: h618-orangepi-zero2w (Kernel 6.1.104-AW64-DBAI)'
          - 'Allwinner: h618-orangepi-zero2w (Kernel 6.1.31-AW64-DBAI)'
      rootfs_size:
        description: 'Ukuran ROOTFS, minimal 640 (756, 1024, 2048, dll)'
        required: true
        default: '1024'
        type: string
      fwinfo:
        description: 'Informasi pemilihan versi firmware'
        required: true
        default: 's905x default adalah untuk STB B860H V1-V2/Dens TV V2Y jadi tinggal pakai setelah burning (HG680-P, Dens TV V2X dan type lain yang memakai SOC AMLOGIC s905x perlu ganti DTB berlaku untuk semua STB AMLOGIC), s905x2=HG680-FJ (B860H V5, Transvision Gen2, CYBORG 001/MNC Playbox perlu ganti DTB), s905x3=X96 Air Gigabit/WECHIP V9 (X96 MAX +, HK1 BOX, H96 MAX X3, dll jugsa sama perlu ganti DTB), s905x4=Akari AX810/Advan AT01 (wifi on gunakan kernel 5.4.x contoh 5.4.279 lengkap driver wifinya), device selain AMLOGIC hanya kompatibel sesuai title firmware'
        type: string

jobs:
  determine_rootfs:
    name: 1. Determine RootFS
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Determine RootFS build matrix
        id: set-matrix
        run: |
          if [[ "${{ github.event.inputs.rootfs_choice }}" == "all" ]]; then
            echo "Akan build semua versi RootFS."
            echo 'matrix={"include":[{"name":"ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz","tag_suffix":"ImmortalWrt-21.02.7-DBAI"},{"name":"OpenWrt-23.05.4-A2OS-armsr-armv8-generic-rootfs.tar.gz","tag_suffix":"OpenWrt-23.05.4-A2OS"},{"name":"OpenWrt-23.05.4-ALKHANET-armsr-armv8-generic-rootfs.tar.gz","tag_suffix":"OpenWrt-23.05.4-ALKHANET"},{"name":"OpenWrt-23.05.5-ALKHANET-armsr-armv8-generic-rootfs.tar.gz","tag_suffix":"OpenWrt-23.05.5-ALKHANET"},{"name":"OpenWrt-23.05.5-InsomWRT-armsr-armv8-generic-rootfs.tar.gz","tag_suffix":"OpenWrt-23.05.5-InsomWRT"}]}' >> $GITHUB_OUTPUT
          elif [[ "${{ github.event.inputs.rootfs_choice }}" == "custom" ]]; then
            CUSTOM_URL="${{ github.event.inputs.custom_rootfs_url }}"
            if [[ -z "$CUSTOM_URL" ]]; then
              echo "Error: Opsi 'custom' dipilih tetapi tidak ada URL yang diberikan."
              exit 1
            fi
            FILENAME=$(basename "$CUSTOM_URL")
            CLEANED_NAME=$(echo "$FILENAME" | sed -e 's/-rootfs//g' -e 's|_rootfs||g' -e 's/\.tar\.gz$//' -e 's/\.img\.gz$//' -e 's/\.zip$//')
            TAG_SUFFIX="Custom-$CLEANED_NAME"
            TARGET_FILENAME="custom-rootfs.tar.gz"
            echo "Akan build RootFS kustom dari URL: $CUSTOM_URL"
            echo "matrix={\"include\":[{\"name\":\"$TARGET_FILENAME\",\"tag_suffix\":\"$TAG_SUFFIX\"}]}" >> $GITHUB_OUTPUT
          else
            echo "Akan build RootFS: ${{ github.event.inputs.rootfs_choice }}"
            TAG_SUFFIX=""
            if [[ "${{ github.event.inputs.rootfs_choice }}" == "ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz" ]]; then
              TAG_SUFFIX="ImmortalWrt-21.02.7-DBAI"
            elif [[ "${{ github.event.inputs.rootfs_choice }}" == "OpenWrt-23.05.4-A2OS-armsr-armv8-generic-rootfs.tar.gz" ]]; then
              TAG_SUFFIX="OpenWrt-23.05.4-A2OS"
            elif [[ "${{ github.event.inputs.rootfs_choice }}" == "OpenWrt-23.05.4-ALKHANET-armsr-armv8-generic-rootfs.tar.gz" ]]; then
              TAG_SUFFIX="OpenWrt-23.05.4-ALKHANET"
            elif [[ "${{ github.event.inputs.rootfs_choice }}" == "OpenWrt-23.05.5-ALKHANET-armsr-armv8-generic-rootfs.tar.gz" ]]; then
              TAG_SUFFIX="OpenWrt-23.05.5-ALKHANET"
            else
              TAG_SUFFIX="OpenWrt-23.05.5-InsomWRT"
            fi
            echo "matrix={\"include\":[{\"name\":\"${{ github.event.inputs.rootfs_choice }}\",\"tag_suffix\":\"$TAG_SUFFIX\"}]}" >> $GITHUB_OUTPUT
          fi

  build_ipk:
    name: 2. Build Firmware
    needs: determine_rootfs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.determine_rootfs.outputs.matrix) }}
    steps:
      - name: Pembersihan dan Instalasi Prasyarat Umum
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install jq lolcat build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget aria2
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      # <-- PERUBAHAN: Langkah ini sekarang kondisional -->
      - name: Instalasi Prasyarat Unduhan Khusus (jika perlu)
        if: github.event.inputs.rootfs_choice == 'custom' && (contains(github.event.inputs.custom_rootfs_url, 'drive.google.com') || contains(github.event.inputs.custom_rootfs_url, 'mega.nz'))
        run: |
          echo "Menginstal prasyarat untuk Google Drive atau Mega..."
          if [[ "${{ github.event.inputs.custom_rootfs_url }}" =~ "drive.google.com" ]]; then
            pip3 install gdown
          fi
          if [[ "${{ github.event.inputs.custom_rootfs_url }}" =~ "mega.nz" ]]; then
            sudo -E apt-get -y install megatools
          fi

      - name: Checkout Repositori
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Cache repositori ULO
        uses: actions/cache@v4
        with:
          path: |
            core/
            rootfs/
            device/
          key: ${{ runner.os }}-ulo-repo-${{ hashFiles('ulo') }}

      - name: Initial Setup & RootFS Download
        run: |
          sudo ./ulo -y
      
      - name: Download Custom RootFS (if selected)
        if: github.event.inputs.rootfs_choice == 'custom'
        run: |
          URL="${{ github.event.inputs.custom_rootfs_url }}"
          OUTPUT_FILE="rootfs/${{ matrix.name }}"
          
          echo "Mendeteksi jenis tautan dari: $URL"
          sudo mkdir -p rootfs

          if [[ "$URL" =~ "drive.google.com" ]]; then
            echo "Tautan Google Drive terdeteksi. Menggunakan gdown..."
            sudo gdown --output "$OUTPUT_FILE" "$URL"
          elif [[ "$URL" =~ "mega.nz" ]]; then
            echo "Tautan Mega.nz terdeteksi. Menggunakan megadl..."
            TEMP_DIR=$(mktemp -d)
            sudo megadl --path "$TEMP_DIR" "$URL"
            DOWNLOADED_FILE=$(find "$TEMP_DIR" -type f -print -quit)
            if [ -f "$DOWNLOADED_FILE" ]; then
              sudo mv "$DOWNLOADED_FILE" "$OUTPUT_FILE"
              sudo rm -rf "$TEMP_DIR"
            else
              echo "Gagal menemukan file yang diunduh dari Mega."
              exit 1
            fi
          else
            echo "Tautan langsung terdeteksi. Menggunakan aria2c..."
            sudo aria2c --quiet=true -x 16 -s 16 -k 1M -d "rootfs" -o "${{ matrix.name }}" "$URL"
          fi
          
          echo "Download complete. File saved as $OUTPUT_FILE"

      - name: Membangun Semua Device (jika 'all' dipilih)
        if: github.event.inputs.device_choice == 'all'
        run: |
          DEVICE_LIST=$(cat <<EOF
          {"device":"s905x","kernel":"6.1.66-DBAI"}
          {"device":"s905x","kernel":"4.9.337"}
          {"device":"s905x2","kernel":"6.1.66-DBAI"}
          {"device":"s905x2","kernel":"5.4.279"}
          {"device":"s905x2","kernel":"4.9.337"}
          {"device":"s905x3","kernel":"6.1.66-DBAI"}
          {"device":"s905x4","kernel":"6.1.66-DBAI"}
          {"device":"s905x4","kernel":"5.4.279"}
          {"device":"rk3588s-orangepi-5","kernel":"5.10.160-rk35v-dbai"}
          {"device":"rk3566-orangepi-3b","kernel":"5.10.160-rk35v-dbai"}
          {"device":"rk3588-orangepi-5-max","kernel":"5.10.160-rk35v-dbai"}
          {"device":"rk3588-orangepi-5-plus","kernel":"5.10.160-rk35v-dbai"}
          {"device":"h618-orangepi-zero3","kernel":"6.1.104-AW64-DBAI"}
          {"device":"h618-orangepi-zero3","kernel":"6.1.31-AW64-DBAI"}
          {"device":"a64-bananapi-m64","kernel":"6.1.104-AW64-DBAI"}
          {"device":"a64-bananapi-m64","kernel":"6.1.31-AW64-DBAI"}
          {"device":"a64-nanopi-a64","kernel":"6.1.104-AW64-DBAI"}
          {"device":"a64-nanopi-a64","kernel":"6.1.31-AW64-DBAI"}
          {"device":"h313-x96q-lpddr3","kernel":"6.1.104-AW64-DBAI"}
          {"device":"h313-x96q-lpddr3","kernel":"6.1.31-AW64-DBAI"}
          {"device":"h5-orangepi-pc2","kernel":"6.1.104-AW64-DBAI"}
          {"device":"h5-orangepi-pc2","kernel":"6.1.31-AW64-DBAI"}
          {"device":"h5-orangepi-prime","kernel":"6.1.104-AW64-DBAI"}
          {"device":"h5-orangepi-prime","kernel":"6.1.31-AW64-DBAI"}
          {"device":"h5-orangepi-zeroplus","kernel":"6.1.104-AW64-DBAI"}
          {"device":"h5-orangepi-zeroplus","kernel":"6.1.31-AW64-DBAI"}
          {"device":"h5-orangepi-zeroplus2","kernel":"6.1.104-AW64-DBAI"}
          {"device":"h5-orangepi-zeroplus2","kernel":"6.1.31-AW64-DBAI"}
          {"device":"h6-orangepi-1plus","kernel":"6.1.104-AW64-DBAI"}
          {"device":"h6-orangepi-1plus","kernel":"6.1.31-AW64-DBAI"}
          {"device":"h6-orangepi-3","kernel":"6.1.104-AW64-DBAI"}
          {"device":"h6-orangepi-3","kernel":"6.1.31-AW64-DBAI"}
          {"device":"h6-orangepi-3lts","kernel":"6.1.104-AW64-DBAI"}
          {"device":"h6-orangepi-3lts","kernel":"6.1.31-AW64-DBAI"}
          {"device":"h6-orangepi-lite2","kernel":"6.1.104-AW64-DBAI"}
          {"device":"h6-orangepi-lite2","kernel":"6.1.31-AW64-DBAI"}
          {"device":"h6-tanix-tx6","kernel":"6.1.104-AW64-DBAI"}
          {"device":"h6-tanix-tx6","kernel":"6.1.31-AW64-DBAI"}
          {"device":"h616-orangepi-zero2","kernel":"6.1.104-AW64-DBAI"}
          {"device":"h616-orangepi-zero2","kernel":"6.1.31-AW64-DBAI"}
          {"device":"h616-x96-mate","kernel":"6.1.104-AW64-DBAI"}
          {"device":"h616-x96-mate","kernel":"6.1.31-AW64-DBAI"}
          {"device":"h618-orangepi-zero2w","kernel":"6.1.104-AW64-DBAI"}
          {"device":"h618-orangepi-zero2w","kernel":"6.1.31-AW64-DBAI"}
          EOF
          )

          echo "$DEVICE_LIST" | while read -r device_config; do
            if [ -z "$device_config" ]; then continue; fi
            DEVICE=$(echo "$device_config" | jq -r .device)
            KERNEL=$(echo "$device_config" | jq -r .kernel)
            echo "=========================================================="
            echo "Membangun: Device=$DEVICE, Kernel=$KERNEL, RootFS=${{ matrix.name }}"
            echo "=========================================================="
            sudo ./ulo -m "$DEVICE" -r "${{ matrix.name }}" -k "$KERNEL" -s "${{ github.event.inputs.rootfs_size }}"
            echo "Membuat artefak untuk $DEVICE..."
            mkdir -p ./artifact/"$DEVICE"
            cp -rf ./out/"$DEVICE"/* ./artifact/"$DEVICE"/ || echo "Tidak ada file output untuk disalin dari $DEVICE"
          done

      - name: Membangun Device Spesifik (jika bukan 'all')
        if: github.event.inputs.device_choice != 'all'
        run: |
          CHOICE="${{ github.event.inputs.device_choice }}"
          DEVICE=$(echo "$CHOICE" | sed -n 's/.*: \(.*\) (.*/\1/p')
          KERNEL=$(echo "$CHOICE" | sed -n 's/.*(Kernel \(.*\))/\1/p')
          
          echo "=========================================================="
          echo "Pilihan Pengguna: $CHOICE"
          echo "Hasil Ekstraksi -> Device: $DEVICE, Kernel: $KERNEL"
          echo "Membangun untuk RootFS: ${{ matrix.name }}"
          echo "=========================================================="
          
          sudo ./ulo -m "$DEVICE" -r "${{ matrix.name }}" -k "$KERNEL" -s "${{ github.event.inputs.rootfs_size }}"
          
          echo "Membuat artefak untuk $DEVICE..."
          mkdir -p ./artifact/"$DEVICE"
          cp -rf ./out/"$DEVICE"/* ./artifact/"$DEVICE"/ || echo "Tidak ada file output untuk disalin dari $DEVICE"

      - name: Mengirim Paket
        uses: actions/upload-artifact@v4
        with:
          name: openwrt_package_${{ matrix.tag_suffix }}
          path: ./artifact/

  upload_release:
    name: 3. Create Release
    needs: [determine_rootfs, build_ipk]
    if: success()
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.determine_rootfs.outputs.matrix) }}
    steps:
      - name: Checkout Repositori
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Unduh artefak untuk ${{ matrix.tag_suffix }}
        uses: actions/download-artifact@v4
        with:
          name: openwrt_package_${{ matrix.tag_suffix }}
          path: artifacts

      - name: Gabungkan artefak
        run: |
          mkdir -p combined_artifact
          find ./artifacts -type f -exec mv {} ./combined_artifact/ \;
          echo "Isi folder yang akan dirilis:"
          ls -la combined_artifact/

      - name: Dapatkan Tanggal Saat Ini
        id: date
        run: |
          sudo apt-get install -y locales
          sudo locale-gen id_ID.UTF-8
          export LC_TIME=id_ID.UTF-8
          export TZ="Asia/Jakarta"
          bulan=$(date +%B)
          tanggal=$(date +%d)
          tahun=$(date +%Y)
          echo "release_tag=${{ matrix.tag_suffix }}_ULO-RELEASE_${bulan}-${tanggal}-${tahun}" >> $GITHUB_OUTPUT

      - name: Unggah aset rilis
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: combined_artifact/*
          tag: ${{ steps.date.outputs.release_tag }}
          file_glob: true
          overwrite: true
          body: |
            ## Rilis OpenWrt untuk Berbagai Perangkat SBC dan STB
            ### Informasi firmware OpenWrt
            - Firmware ini dibuild menggunakan Github Actions dengan RootFS: **${{ matrix.tag_suffix }}**
            - Ukuran ROOTFS: ${{ github.event.inputs.rootfs_size }}
            - Informasi pemilihan versi firmware: ${{ github.event.inputs.fwinfo }}
            - Facebook FP: https://www.facebook.com/armarchindo/
            - Blog: https://dbai-team.com
            - Pertanyaan dan diskusi ke grup Discord DBAI: https://discord.gg/BXNzaJFTPP
