name: ULO Autobuilder v2

on:
  workflow_dispatch:
    inputs:
      kernel:
        description: 'Versi Kernel (contoh: 6.6.6, 6.1.31-localversion)'
        required: true
        default: '6.1.66-DBAI'
        type: string
      rootfs:
        description: 'File ROOTFS (contoh: ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz)'
        required: true
        default: 'ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz'
        type: string
      rootfs_size:
        description: 'Ukuran ROOTFS, minimal 640 (756, 1024, 2048, dll)'
        required: true
        default: '1024'
        type: string
      fwinfo:
        description: 'Informasi Firmware'
        required: true
        default: 'catatan rilis'
        type: string

jobs:
  build_ipk:
    permissions:
      contents: write
    name: ULO Autobuilder
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device:
          - s905x
          - s905x2
          # Tambahkan perangkat lain setelah testing berhasil
    steps:
      - name: Pembersihan dan Instalasi Prasyarat
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install jq lolcat build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget aria2
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Checkout Repositori
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Cache repositori ULO
        uses: actions/cache@v4
        with:
          path: |
            core/
            rootfs/
            device/
          key: ${{ runner.os }}-ulo-repo-${{ hashFiles('ulo') }}

      - name: Patching ULO
        run: |
          mv ./.github/workflows/ULO_Workflow.patch ./ULO_Workflow.patch
          patch -p1 < ./ULO_Workflow.patch

      - name: Membangun OpenWrt
        run: |
          echo "Memeriksa ketersediaan repositori ULO..."
          curl -I https://codeload.github.com/armarchindo/ULO-repository/zip/refs/heads/main
          sudo ./ulo -y -m ${{ matrix.device }} -r ${{ inputs.rootfs }} -k ${{ inputs.kernel }} -s ${{ inputs.rootfs_size }} || \
          (sleep 5 && sudo aria2c --max-tries=3 --retry-wait=5 https://codeload.github.com/armarchindo/ULO-repository/zip/refs/heads/main)
          echo "Pembangunan selesai atau gagal. Memeriksa direktori output..."
          ls -la ./out/

      - name: Membuat Artefak Paket
        if: success() || failure()
        run: |
          mkdir -p ./artifact/${{ matrix.device }}
          cp -rf ./out/${{ matrix.device }}/* ./artifact/${{ matrix.device }}/ || true

      - name: Mengirim Paket
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: openwrt_package_${{ matrix.device }}
          path: ./artifact/${{ matrix.device }}/*

  upload_release:
    needs: build_ipk
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositori
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Unduh semua artefak
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Gabungkan artefak
        run: |
          mkdir -p combined_artifact
          for device in s905x s905x2; do
            cp -rf artifacts/openwrt_package_${device}/* combined_artifact/ || true
          done
          ls -la combined_artifact/

      - name: Dapatkan Tanggal Saat Ini
        id: date
        run: |
          sudo apt-get install -y locales
          sudo locale-gen id_ID.UTF-8
          export LC_TIME=id_ID.UTF-8
          bulan=$(date +%B)
          tanggal=$(date +%d)
          tahun=$(date +%Y)
          echo "release_tag=ULO-RELEASE_${bulan}-${tanggal}-${tahun}" >> $GITHUB_OUTPUT

      - name: Unggah aset rilis
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: combined_artifact/*
          tag: ${{ steps.date.outputs.release_tag }}
          file_glob: true
          overwrite: true
          body: |
            ## Rilis OpenWrt untuk Berbagai Perangkat
            Rilis ULO-Builder dari Workflow Github
            ### Informasi Gambar OpenWrt
            - Versi kernel: ${{ inputs.kernel }}
            - File ROOTFS: ${{ inputs.rootfs }}
            - Ukuran ROOTFS: ${{ inputs.rootfs_size }}
            - Informasi Firmware: ${{ inputs.fwinfo }}
            - Perangkat yang disertakan: s905x, s905x2
