name: ULO Autobuilder v2 (Final, Fast & Targeted)

on:
  workflow_dispatch:
    inputs:
      rootfs_size:
        description: 'Ukuran ROOTFS, minimal 640 (756, 1024, 2048, dll)'
        required: true
        default: '1024'
        type: string
      fwinfo:
        description: 'Informasi Firmware'
        required: true
        default: 'catatan rilis'
        type: string

jobs:
  # JOB 1: Membuat Draf Rilis
  create_release:
    name: 1. Create Draft Release
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    outputs:
      upload_url: ${{ steps.create_release_step.outputs.upload_url }}
      release_tag: ${{ steps.get_date.outputs.release_tag }}
    steps:
      - name: Checkout Repositori
        uses: actions/checkout@v4

      - name: Dapatkan Tanggal dan Buat Tag
        id: get_date
        run: |
          export TZ="Asia/Jakarta"
          bulan=$(date +%B)
          tanggal=$(date +%d)
          tahun=$(date +%Y)
          echo "release_tag=ULO-RELEASE_${bulan}-${tanggal}-${tahun}" >> $GITHUB_OUTPUT

      - name: Create Draft Release via GH CLI
        id: create_release_step
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE_TAG="${{ steps.get_date.outputs.release_tag }}"
          RELEASE_BODY=$(cat <<EOF
          ## Rilis OpenWrt untuk Berbagai Perangkat SBC dan STB
          Firmware ini dibuild menggunakan Github Actions
          ### Informasi Firmware OpenWrt
          - Ukuran ROOTFS: ${{ inputs.rootfs_size }}
          - Informasi Firmware: ${{ inputs.fwinfo }}
          EOF
          )
          
          gh release create "$RELEASE_TAG" --draft --title "Rilis ULO Autobuild | $RELEASE_TAG" --notes "$RELEASE_BODY"
          
          UPLOAD_URL=$(gh release view "$RELEASE_TAG" --json uploadUrl -q .uploadUrl)
          echo "upload_url=$UPLOAD_URL" >> $GITHUB_OUTPUT

  # JOB 2: Membangun firmware dengan pencarian file yang cepat dan tertarget
  build_and_upload:
    name: 2. Build and Upload Firmware
    needs: create_release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        config:
          # --- SoC: Amlogic ---
          - { device: s905x, kernel: '6.1.66-DBAI' }
        rootfs:
          - 'ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz'
          - 'OpenWrt-23.05.4-A2OS-armsr-armv8-generic-rootfs.tar.gz'
    steps:
      - name: Pembersihan dan Instalasi Prasyarat
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install git
      - name: Checkout Repositori
        uses: actions/checkout@v4
      - name: Patching ULO
        run: |
          if [ -f ./.github/workflows/ULO_Workflow.patch ]; then
            mv ./.github/workflows/ULO_Workflow.patch ./ULO_Workflow.patch
            patch -p1 < ./ULO_Workflow.patch
          fi
      
      - name: Membangun OpenWrt
        run: |
          sudo ./ulo -y -m ${{ matrix.config.device }} -r ${{ matrix.rootfs }} -k ${{ matrix.config.kernel }} -s ${{ inputs.rootfs_size }}

      # --- PERUBAHAN UTAMA: PENCARIAN FILE KEMBALI CEPAT DAN TERTARGET ---
      - name: Find Firmware File
        id: find_file
        run: |
          # Langkah ini mencari HANYA di direktori output yang sudah Anda konfirmasi.
          SEARCH_DIR="${{ runner.workspace }}/out/${{ matrix.config.device }}"
          
          echo "Mencari file di direktori: $SEARCH_DIR"
          
          # 'find' di sini akan berjalan instan. sudo tetap dipakai untuk jaga-jaga masalah izin file.
          FILE_PATH=$(sudo find "$SEARCH_DIR" -maxdepth 1 -name "*.img.gz" -type f)
          
          if [ -z "$FILE_PATH" ]; then
            echo "FATAL ERROR: File .img.gz tidak ditemukan di direktori yang diharapkan: $SEARCH_DIR"
            echo "--- Isi Direktori (jika ada) ---"
            ls -laR "$SEARCH_DIR" || echo "Direktori $SEARCH_DIR tidak bisa diakses atau tidak ada."
            echo "--------------------------------"
            exit 1
          fi
          
          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV
          echo "File ditemukan di: $FILE_PATH"

      - name: Upload Firmware to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ${{ env.FILE_PATH }}
          asset_name: ${{ matrix.config.device }}_${{ matrix.config.kernel }}_${{ matrix.rootfs }}.img.gz
          asset_content_type: application/gzip

  # JOB 3: Mempublikasikan rilis
  publish_release:
    name: 3. Publish Release
    needs: [create_release, build_and_upload]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: success()
    steps:
      - name: Checkout Repositori
        uses: actions/checkout@v4
        
      - name: Publish the release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release edit ${{ needs.create_release.outputs.release_tag }} --draft=false
