name: ULO Autobuilder v2

# Referensi Daftar untuk Kemudahan Pengeditan
# DEVICES: s905x, s905x2, h618-orangepi-zero3, rk3588s-orangepi-5
# KERNELS: 6.1.66-DBAI, 5.4.279, 4.9.337, 6.1.104-AW64-DBAI, 6.1.31-AW64-DBAI, 5.10.160-rk35v-dbai
# ROOTFS_FILES: ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz, OpenWrt-23.05.4-A2OS-armsr-armv8-generic-rootfs.tar.gz
# Untuk menambah device/kernel/rootfs:
# 1. Tambahkan ke referensi di atas.
# 2. Tambahkan kombinasi valid di strategy.matrix.include di bawah.
# 3. Pastikan kombinasi sesuai dengan aturan perangkat.

on:
  workflow_dispatch:
    inputs:
      rootfs_size:
        description: 'Ukuran ROOTFS, minimal 640 (756, 1024, 2048, dll)'
        required: true
        default: '1024'
        type: string
      fwinfo:
        description: 'Informasi Firmware'
        required: true
        default: 'catatan rilis'
        type: string

jobs:
  build_ipk:
    permissions:
      contents: write
    name: ULO Autobuilder
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # Device: s905x (Kernel: 6.1.66-DBAI, 4.9.337)
          - device: s905x
            kernel: '6.1.66-DBAI'
            rootfs: 'ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz'
          - device: s905x
            kernel: '6.1.66-DBAI'
            rootfs: 'OpenWrt-23.05.4-A2OS-armsr-armv8-generic-rootfs.tar.gz'
          - device: s905x
            kernel: '4.9.337'
            rootfs: 'ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz'
          - device: s905x
            kernel: '4.9.337'
            rootfs: 'OpenWrt-23.05.4-A2OS-armsr-armv8-generic-rootfs.tar.gz'
          # Device: s905x2 (Kernel: 6.1.66-DBAI, 5.4.279, 4.9.337)
          - device: s905x2
            kernel: '6.1.66-DBAI'
            rootfs: 'ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz'
          - device: s905x2
            kernel: '6.1.66-DBAI'
            rootfs: 'OpenWrt-23.05.4-A2OS-armsr-armv8-generic-rootfs.tar.gz'
          - device: s905x2
            kernel: '5.4.279'
            rootfs: 'ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz'
          - device: s905x2
            kernel: '5.4.279'
            rootfs: 'OpenWrt-23.05.4-A2OS-armsr-armv8-generic-rootfs.tar.gz'
          - device: s905x2
            kernel: '4.9.337'
            rootfs: 'ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz'
          - device: s905x2
            kernel: '4.9.337'
            rootfs: 'OpenWrt-23.05.4-A2OS-armsr-armv8-generic-rootfs.tar.gz'
          # Device: h618-orangepi-zero3 (Kernel: 6.1.104-AW64-DBAI, 6.1.31-AW64-DBAI)
          - device: h618-orangepi-zero3
            kernel: '6.1.104-AW64-DBAI'
            rootfs: 'ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz'
          - device: h618-orangepi-zero3
            kernel: '6.1.104-AW64-DBAI'
            rootfs: 'OpenWrt-23.05.4-A2OS-armsr-armv8-generic-rootfs.tar.gz'
          - device: h618-orangepi-zero3
            kernel: '6.1.31-AW64-DBAI'
            rootfs: 'ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz'
          - device: h618-orangepi-zero3
            kernel: '6.1.31-AW64-DBAI'
            rootfs: 'OpenWrt-23.05.4-A2OS-armsr-armv8-generic-rootfs.tar.gz'
          # Device: rk3588s-orangepi-5 (Kernel: 5.10.160-rk35v-dbai)
          - device: rk3588s-orangepi-5
            kernel: '5.10.160-rk35v-dbai'
            rootfs: 'ImmortalWrt-21.02.7-DBAI-armvirt-rootfs.tar.gz'
          - device: rk3588s-orangepi-5
            kernel: '5.10.160-rk35v-dbai'
            rootfs: 'OpenWrt-23.05.4-A2OS-armsr-armv8-generic-rootfs.tar.gz'
    steps:
      - name: Pembersihan dan Instalasi Prasyarat
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get update
          sudo -E apt-get -y install jq lolcat build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev rsync unzip zlib1g-dev file wget aria2
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Checkout Repositori
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Cache repositori ULO
        uses: actions/cache@v4
        with:
          path: |
            core/
            rootfs/
            device/
          key: ${{ runner.os }}-ulo-repo-${{ hashFiles('ulo') }}

      - name: Patching ULO
        run: |
          mv ./.github/workflows/ULO_Workflow.patch ./ULO_Workflow.patch
          patch -p1 < ./ULO_Workflow.patch

      - name: Membangun OpenWrt
        run: |
          echo "Memeriksa ketersediaan repositori ULO..."
          curl -I https://codeload.github.com/armarchindo/ULO-repository/zip/refs/heads/main
          sudo ./ulo -y -m ${{ matrix.device }} -r ${{ matrix.rootfs }} -k ${{ matrix.kernel }} -s ${{ inputs.rootfs_size }} || \
          (sleep 5 && sudo aria2c --max-tries=3 --retry-wait=5 https://codeload.github.com/armarchindo/ULO-repository/zip/refs/heads/main)
          echo "Pembangunan selesai atau gagal. Memeriksa direktori output..."
          ls -la ./out/

      - name: Membuat Artefak Paket
        if: success() || failure()
        run: |
          mkdir -p ./artifact/${{ matrix.device }}/${{ matrix.kernel }}-${{ matrix.rootfs }}
          cp -rf ./out/${{ matrix.device }}/* ./artifact/${{ matrix.device }}/${{ matrix.kernel }}-${{ matrix.rootfs }}/ || true

      - name: Mengirim Paket
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: openwrt_package_${{ matrix.device }}_${{ matrix.kernel }}_${{ matrix.rootfs }}
          path: ./artifact/${{ matrix.device }}/${{ matrix.kernel }}-${{ matrix.rootfs }}/*

  upload_release:
    needs: build_ipk
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositori
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Unduh semua artefak
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Gabungkan artefak
        run: |
          mkdir -p combined_artifact
          for artifact in artifacts/openwrt_package_*; do
            cp -rf "$artifact"/* combined_artifact/ || true
          done
          ls -la combined_artifact/

      - name: Dapatkan Tanggal Saat Ini
        id: date
        run: |
          sudo apt-get install -y locales
          sudo locale-gen id_ID.UTF-8
          export LC_TIME=id_ID.UTF-8
          bulan=$(date +%B)
          tanggal=$(date +%d)
          tahun=$(date +%Y)
          echo "release_tag=ULO-RELEASE_${bulan}-${tanggal}-${tahun}" >> $GITHUB_OUTPUT

      - name: Unggah aset rilis
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: combined_artifact/*
          tag: ${{ steps.date.outputs.release_tag }}
          file_glob: true
          overwrite: true
          body: |
            ## Rilis OpenWrt untuk Berbagai Perangkat SBC dan STB
            Firmware ini di-Build menggunakan Workflow Github
            ### Informasi Firmware OpenWrt
            - Ukuran ROOTFS: ${{ inputs.rootfs_size }}
            - Informasi Firmware: ${{ inputs.fwinfo }}
